version: 2

jobs:
    benchmark_machine:
        machine: true
        steps:
        - checkout
        - run:
            name: Install/Run Geekbench on the raw machine
            command: |
                mkdir logs
                ./geekbench/geekbench4 > logs/export-results-1.txt &
                ./geekbench/geekbench4 > logs/export-results-2.txt &
                ./geekbench/geekbench4 > logs/export-results-3.txt &
                ./geekbench/geekbench4 > logs/export-results-4.txt &

                wait
        - store_artifacts:
            path: logs
    benchmark_limited_container:
        machine: true
        steps:
        - checkout
        - run:
            name: Install/Run Geekbench on a limited CPU container, with no swap
            command: |
                docker run \
                    -v $(pwd)/geekbench:/geekbench \
                    -it --rm \
                    --cpus=".1" \
                    --memory="500m" \
                    ubuntu \
                    /geekbench/geekbench4
workflows:
  version: 2
  benchmark_machine:
    jobs:
      - benchmark_machine
      #- benchmark_limited_container
