version: 2

jobs:
    benchmark_machine:
        machine: true
        steps:
        - checkout
        - run:
            name: Install/Run Geekbench on the raw machine
            command: ./geekbench/geekbench4
    benchmark_limited_container:
        machine: true
        steps:
        - checkout
        - run:
            name: Install/Run Geekbench on a limited CPU container, with no swap
            command: |
                docker run \
                    -v $(pwd)/geekbench:/geekbench \
                    -it --rm \
                    --cpus=".5" \
                    --memory="2000m" \
                    ubuntu \
                    /geekbench/geekbench4
workflows:
  version: 2
  benchmark_machine:
    jobs:
      - benchmark_machine
      - benchmark_limited_container
